debci-test: accept run-id as a command line parameter

diff --git a/bin/debci-test b/bin/debci-test
--- a/bin/debci-test
+++ b/bin/debci-test
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-short_options='ot:p:'
-long_options='print-output,trigger:,pin-packages:'
+short_options='ot:p:i:'
+long_options='print-output,trigger:,pin-packages:,run-id:'
 
 usage() {
   cat <<EOF
@@ -19,6 +19,9 @@ Options:
       Force specific packages to be installed from the given RELEASE. The
       format is the same as the --pin-packages option from autopkgtest. RELEASE
       will be automatically addded to the testbed APT sources.
+  -i ID, --run-id ID
+      Use the specific ID as the run id for this test run, instead of
+      generating one based on the current date.
 $@
 EOF
 }
@@ -31,18 +34,23 @@ debci_base_dir=$(readlink -f $(dirname $(readlink -f $0))/..)
 
 process_package() {
   # output directory for test-package/autopkgtest
-  run_id=$(date +%Y%m%d_%H%M%S)
   local base_dir="$(autopkgtest_incoming_dir_for_package "$pkg")"
-  adt_out_dir="${base_dir}/${run_id}"
 
-  inc=0
-  orig_run_id="$run_id"
-  while [ -d "$adt_out_dir" ]; do
-    # this in *very* unlikely to happen in production, but we need this for the
-    # test suite
-    run_id="${orig_run_id}.${inc}"
+  if [ -n "${run_id:-}" ]; then
     adt_out_dir="${base_dir}/${run_id}"
-  done
+  else
+    run_id=$(date +%Y%m%d_%H%M%S)
+    adt_out_dir="${base_dir}/${run_id}"
+
+    inc=0
+    orig_run_id="$run_id"
+    while [ -d "$adt_out_dir" ]; do
+      # this in *very* unlikely to happen in production, but we need this for the
+      # test suite
+      run_id="${orig_run_id}.${inc}"
+      adt_out_dir="${base_dir}/${run_id}"
+    done
+  fi
 
   mkdir -p "$(dirname $adt_out_dir)"
   start_timestamp=$(date +%s)
@@ -104,6 +112,16 @@ while true; do
       shift
       release=$(echo "$pin" | cut -d = -f 1)
       options="$options --add-apt-release=$release --pin-packages=$pin"
+      ;;
+    -i|--run-id)
+      run_id="$1"
+      if echo "$run_id" | grep -q '^[0-9]\{8\}_[0-9]\{6\}$' ; then
+        : ok
+      else
+        echo "E: invalid run-id: $run_id (format needs to be YYYYMMDD_HHMMSS)"
+        exit 1
+      fi
+      shift
       ;;
     --)
       break
