backends/lxc: retry `apt-get update` until it works
Most of the time when the testbed setup fails on production is during `apt-get
update`.

diff --git a/backends/lxc/create-testbed b/backends/lxc/create-testbed
--- a/backends/lxc/create-testbed
+++ b/backends/lxc/create-testbed
@@ -91,7 +91,10 @@ if [ "$distro" = debian ]; then
 deb http://incoming.debian.org/debian-buildd $buildd_suite main
 deb-src http://incoming.debian.org/debian-buildd $buildd_suite main
 EOF
-  chroot "$rootfs" apt-get update
+  while ! chroot "$rootfs" apt-get update; do
+    echo "I: apt-get update failed, let's wait some time and try again "
+    sleep 10s
+  done
 fi
 
 # configure guest proxy
