backends/schroot/list-dependencies: Fix for nonexisting binaries
Ignore individual apt-get failures as that gets called for binaries which don't
exist on the selected architecture. Fixes operation for e. g. glib2.0.

diff --git a/backends/schroot/list-dependencies b/backends/schroot/list-dependencies
--- a/backends/schroot/list-dependencies
+++ b/backends/schroot/list-dependencies
@@ -28,7 +28,8 @@ binaries=$(list_binaries "$pkg")
 {
   if ! schroot -d / -c "$debci_chroot_name" -u root -- apt-get install --quiet --assume-yes --simulate $binaries 2>&1; then
     for binary in $binaries; do
-      schroot -d / -c "$debci_chroot_name" -u root -- apt-get -q -y --simulate  install $binary 2>&1
+      # this can fail for binaries which don't exist on this architecture
+      schroot -d / -c "$debci_chroot_name" -u root -- apt-get -q -y --simulate install $binary 2>&1 || true
     done
   fi
 } | \
